### ISSUE TITLE
mgl03_1.4.7_0115_mod20201222 uart file not exist

### ISSUE THREAD

**Issue by lacikasimon** [serrj-sv/lumi.gateway.mgl03#12]

**Comment by zvldz** [comment]
It will probably be uploaded tomorrow.

**Comment by zvldz** [comment]
You can also use instruction https://gist.github.com/zvldz/b40b4873e3c4c1a64ac536e8ce5dbdad. It will appear here soon

**Comment by lacikasimon** [comment]
Thank you,
works
