### ISSUE TITLE
Which UART should I order ?

### ISSUE THREAD

**Issue by Tatoo974** [serrj-sv/lumi.gateway.mgl03#16]
Hi , sorry I’m not used with UART usb stick. Could someone help me to choose on AliExpress a good one for soldering my gateway 3 ? Thanks a lot

**Comment by Yiivgeny** [comment]
Works for me https://aliexpress.ru/item/32673467746.html
![изображение](https://user-images.githubusercontent.com/1321010/104598098-384bd680-5687-11eb-8daf-9815ec16a292.png)

**Comment by Tatoo974** [comment]
Ok thanks a lot !
And I have just to solder the TX,RX and GND to the board at the righ places ? How to choose 3.3v mode ?
Should I have to buy an external power supply ?
Thank you

**Comment by Yiivgeny** [comment]
I connect TX->RX, RX->TX, GND->GND, gateway connected to USB port on my computer (with inlcuded cable), uart stick to another port, and it's all.

**Comment by Tatoo974** [comment]
Thanks a lot !
