### ISSUE TITLE
Wrong firmware file header!

### ISSUE THREAD

**Issue by lastoks** [serrj-sv/lumi.gateway.mgl03#7]
Hi,
when I choose the firmware file "mgl03_1.4.7_0065_mod20201116.uart" I get an error message "Wrong firmware file header!".

Best regards 
Lars

**Comment by serrj-sv** [comment]
> Hi,
> when I choose the firmware file "mgl03_1.4.7_0065_mod20201116.uart" I get an error message "Wrong firmware file header!".
> 
> Best regards
> Lars

please check https://github.com/serrj-sv/lumi.gateway.mgl03/issues/1

**Comment by lastoks** [comment]
This is really embarrassing. Thanks, it's working fine! 🥇
